// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJjpjychzG4id4yNnjk8UGoLMOP2JMyMc',
    appId: '1:421093586537:web:ad0f4fd1fa0e03c77994f8',
    messagingSenderId: '421093586537',
    projectId: 'contract-d38a1',
    authDomain: 'contract-d38a1.firebaseapp.com',
    storageBucket: 'contract-d38a1.appspot.com',
    measurementId: 'G-28L74419QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDii6D_FmM-32YrzBzRdIi-ucYxI-hfZR4',
    appId: '1:421093586537:android:3e86a8ec3be70e1e7994f8',
    messagingSenderId: '421093586537',
    projectId: 'contract-d38a1',
    storageBucket: 'contract-d38a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3v_JswWE9K9QXPIDKYUJAGPOq811wouw',
    appId: '1:421093586537:ios:7d2eb510b425f9ce7994f8',
    messagingSenderId: '421093586537',
    projectId: 'contract-d38a1',
    storageBucket: 'contract-d38a1.appspot.com',
    iosBundleId: 'com.example.clientProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3v_JswWE9K9QXPIDKYUJAGPOq811wouw',
    appId: '1:421093586537:ios:5ce933a84dfa5b1a7994f8',
    messagingSenderId: '421093586537',
    projectId: 'contract-d38a1',
    storageBucket: 'contract-d38a1.appspot.com',
    iosBundleId: 'com.example.clientProject.RunnerTests',
  );
}
